name = "agency-desktop"
type = "webpack"
account_id = ""
route = ""
zone_id = ""
usage_model = ""
workers_dev = true

[site]
bucket = "./dist"

[build]
command = "npm run build"
publish = "dist"
main = "./dist/index.html"

[build.environment]
NODE_VERSION = "18"
API_BASE_URL = "https://api.yourdomain.com"

[build.upload]
format = "service-worker"