name = 'gestionale-byo'
type = "webpack"
account_id = "3896673f"
workers_dev = false
route = "gestionale-byo.pages.dev/*"
zone_id = "gestionale-byo"
compatibility_date = "2024-03-09"

[site]
bucket = "./dist"

[build]
command = "npm install && npm run build"
upload_dir = "dist"