name = "gestional"
type = "webpack"
account_id = ""
route = ""
zone_id = ""
usage_model = ""
workers_dev = true

[site]
bucket = "./dist"

[build]
command = "npm run build"
publish = "dist"
deploy_command = "npx wrangler pages deploy dist"
path = "/client"

[build.environment]
NODE_VERSION = "18"
API_BASE_URL = "https://gestional.xdcar235.workers.dev"

[workers_site]
entry-point = "workers-site"

[build.upload]
format = "service-worker"

[[rules]]
type = "NavigationRoute"
route = "/.*"
allowlist = ["/", "/index.html"]