name = "gestioal"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2024-03-09"

[site]
bucket = "./dist"

[build]
command = "cd client && npm install && npm run build"
upload_dir = "client/dist"